Test for beamformer modes before attempting to set weight

diff --git a/scripts/k7-beam-weights b/scripts/k7-beam-weights
--- a/scripts/k7-beam-weights
+++ b/scripts/k7-beam-weights
@@ -5,17 +5,22 @@ source functions.sh
 
 kcs_arg_check $# 2
 
-if [ "$#" -eq 2 ]  ; then
-  kcpcmd -i -k weights-get $1 $2 | tr -d '()' | sed -e 's/^!weights-get/#return/'
-else 
-  status=1
+if kcs_is_beamformer ${KATCP_MODE} ; then
+  if [ "$#" -eq 2 ]  ; then
+    kcpcmd -i -k weights-get $1 $2 | tr -d '()' | sed -e 's/^!weights-get/#return/'
+  else 
+    status=1
 
-  kcs_debug "setting $*"
+    kcs_debug "setting $*"
 
-  if kcpcmd -k -t 300 -m weights-set $* ; then
-    status=0
+    if kcpcmd -k -t 300 -m weights-set $* ; then
+      status=0
+    fi
+
+    kcs_corr_log
+    exit $status
   fi
-
-  kcs_corr_log
-  exit $status
-fi
+else
+  echo "#return fail unavailable"
+  kcs_error "beam selection not available in mode ${KATCP_MODE}"
+fi  
